[project]
name = "rime-hokchew"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Leo",email = "im.yczeng@foxmail.com"},
]
dependencies = ["ruamel-yaml>=0.19.1", "pyyaml>=6.0.3"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[project.optional-dependencies]
dev = [
    "mypy>=2.1.0",
    "ruff>=0.15.18",
]
[tool.pdm]
distribution = false
